baseURL = "https://gitecheminvert.com"
enableRobotsTXT = true

defaultContentLanguage = "en"
languageCode = "en-us"
defaultContentLanguageInSubdir = true

pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "Le Gîte du Chemin Vert - Pontlevoy"

# [author]
#   gravatarEmail = "jtamagnan@gmail.com"
#   homepageText = "Jules Tamagnan"
#   name = "Jules Tamagnan"
#   rss = "/posts/index.xml"

[imaging]
 anchor = "smart"
 resampleFilter = "box"
 quality = 75

[outputs]
 home = ["HTML"]
 page = ["HTML"]
 section = ["HTML"]
 taxonomy = ["HTML"]
 taxonomyTerm = ["HTML"]

[params]
 custom_js = ["js/modal.js"]
 # custom_css = ["css/modal.css"]
 description = "Le Gîte du Chemin Vert - Pontlevoy"
 licence = false
 displayPostLanguage = false

 [params.navigation]
   help = "Help"

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[pygmentsOptions]
  linenos = false

[markup.goldmark.renderer]
unsafe= true

[languages]
  [languages.en]
    # title = ""
    weight = 1
    languageName = "English"
    # [languages.en.params]
    #   linkedin = "https://linkedin.com/whoever"
  [languages.fr]
    weight = 2
    languageName = "Français"
    # [languages.fr.params]
    #   linkedin = "https://linkedin.com/fr/whoever"
    #   [languages.fr.params.navigation]
    #     help = "Aide"
  [languages.es]
    weight = 3
    languageName = "Español"